services:
  - type: web
    name: loft-cafe-bot
    env: python
    pythonVersion: 3.12.3
    plan: free
    region: frankfurt
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_GROUP_ID
        value: "941891457"
      - key: ADMIN_SECRET
        sync: false
      - key: PORT
        value: "8000"
      - key: DB_PATH
        value: "data/reviews.db"
    autoDeploy: true
